// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.santablanca.butler.model;

import net.santablanca.butler.model.Trade;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Trade_Roo_Configurable {
    
    declare @type: Trade: @Configurable;
    
}
